const REGISTER_USER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_USER_FAIL = "REGISTER_SUCCESS";
const LOGIN_USER_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_USER_FAIL = "LOGIN_FAIL";
const AUTH_LOADING_ON = "AUTH_LOADING_ON";
const AUTH_LOADING_OFF = "AUTH_LOADING_OFF";

export {
  REGISTER_USER_SUCCESS,
  REGISTER_USER_FAIL,
  LOGIN_USER_FAIL,
  LOGIN_USER_SUCCESS,
  AUTH_LOADING_OFF,
  AUTH_LOADING_ON,
};